### ISSUE TITLE
Problem with topic

### ISSUE THREAD

**Issue by Groofertje** [rdmtc/node-red-contrib-ccu#100]
I found something weird with the topic of the node ccu-rpc-event.

In the node the topic is declared with "${room}/${datapoint}/${datapointType}/${payload}"

If the payload is 0 then the value is not showed into the topic.
This happend with both HMIP-RF as BIDCOS-RF.
But the payload show the value 0
Picture (Node BidCos No payload 0) and (Node HmRFIP No payload 0) 

Also if the node is declared HMIP-RF with the value OPERATING-VOLTAGE then the room and functions are NOT implemented neither into the topic as in the msg 
Picture (Node HmRFIP No room)

Srr for my poor english :)
![Node BidCos No payload 0](https://user-images.githubusercontent.com/25877218/66288879-3cf9da80-e8db-11e9-932f-26ad1b20b28f.png)
![Node HmRFIP No payload 0](https://user-images.githubusercontent.com/25877218/66288880-3cf9da80-e8db-11e9-9568-cd7aceb16c8d.png)
![Node HmRFIP No room](https://user-images.githubusercontent.com/25877218/66288881-3cf9da80-e8db-11e9-9dd0-d0c69a4d0fc3.png)

**Comment by hobbyquaker** [comment]
Should be fixed with node-red-contrib-ccu@3.1.2 / RedMatic@5.2.1

**Comment by Groofertje** [comment]
Tx for the help

Guillaume Swennen

Dit e-mailbericht en alle documenten die ermee verzonden worden, zijn privé en/of vertrouwelijk, worden u onder alle voorbehoud meegedeeld en zijn uitsluitend bestemd voor gebruik door de persoon of de onderneming waaraan ze geadresseerd zijn. Indien deze e-mail verkeerdelijk bij u terechtkomt, gelieve de afzender te verwittigen en deze bestanden van uw computer te verwijderen.

Der Inhalt dieser E-Mail ist vertraulich und oder rechtlich geschützt, und damit ausschließlich für den bezeichneten Adressaten bestimmt. Wenn Sie nicht der vorgesehene Adressat dieser E-Mail oder dessen Vertreter sein sollten, so beachten Sie bitte, dass jede Form der Kenntnisnahme, Veröffentlichung, Vervielfältigung oder Weitergabe des Inhalts dieser E-Mail unzulässig ist. Wir bitten Sie, sich in diesem Fall mit dem Absender der E-Mail in Verbindung zu setzen.

The information contained in this e-mail is intended only for the personal and confidential use of the recipient(s) named above. This communication may contain information that is proprietary, privileged or confidential or otherwise legally exempt from disclosure. If the reader of this e-mail is not the intended recipient or an agent responsible for delivering it to the intended recipient, you are hereby notified that you have received this document in error and that you are not authorized to read, print, retain, copy or disseminate this message or any part of it. If you have received this message in error, please notify the sender immediately by E-Mail

________________________________
Van: Sebastian Raff <notifications@github.com>
Verzonden: Saturday, November 9, 2019 10:43:39 AM
Aan: rdmtc/node-red-contrib-ccu <node-red-contrib-ccu@noreply.github.com>
CC: Guillaume Swennen <guy_swennen@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [rdmtc/node-red-contrib-ccu] Problem with topic (#100)


Should be fixed with node-red-contrib-ccu@3.1.2 / RedMatic@5.2.1
