### ISSUE TITLE
property naming consistency

### ISSUE THREAD

**Issue by dabbelju007** [rdmtc/node-red-contrib-ccu#102]
If you want to use the nodes in a more dynamic way you can use msg.interface, msg.channel and msg.datapoint for example with the setValue Node.

If you do the same with getValue Node it ist msg.iface and not msg.interface.

Enhancement Request 1: Would it be possible to have it the same in all Nodes which support getting the parameters from msg?

Enhancement Request 2: Can it be implemented in the Switch Node to get Node's needed parameters from msg?

**Comment by hobbyquaker** [comment]
created #103 for second request

**Comment by hobbyquaker** [comment]
node-red-contrib-ccu@3.1.2 / RedMatic@5.2.1 should allow to use `msg.interface` on all applicable nodes.
