### ISSUE TITLE
Version 3.1.2 unter RedMatic keine sysvar mehr.

### ISSUE THREAD

**Issue by sblogoshs21** [rdmtc/node-red-contrib-ccu#104]
Hallo zusammen.

Ich hatte bis einschließlich der V. 3.1.1 keine Probleme doch mit RedMatic 5.2.1 kam die CCU  3.1.2 und damit gibt es bei mir keine sysvar Objekte mehr, die Einstellungen unter Node-Red Homematic sind unverändert. Bei den vorhandenen Objekten fehlt in den Einstellungen dann auch die Auswahl der sysvar's!
Aktuell muss ich die Palette einzeln auf den neuesten Stand bringen denn die 5.2.0 von der Node-Red ist die einzige ohne Probleme bei mir.

Hat jemand eine Idee/Lösung für mich?
Vielen Dank schon mal.

**Comment by hobbyquaker** [comment]
@sblogoshs21 Da müsste ich ein Blick ins Log auf Debug Level werfen (https://github.com/rdmtc/RedMatic/wiki/Loglevel)

**Comment by sblogoshs21** [comment]
Hallo. 

Ich helfe ja gerne aber dazu müsste ich dann wohl auf wider die 3.1.2 aktualisieren und wenn ich beim downgrade zuerst wieder die RedMatic 5.2.0 installieren und alle anderen Komponenten einzeln auf den neuesten Stand bringen muss. 
Denn aktuell läuft ja alles ohne Probleme und ich weiß nicht ob es die Arbeit wert ist. Ich bin auch noch recht frisch bei RedMatic, vor kaum 2 Wochen lief noch alles über Homebridge. 

Es sei denn es gibt ein downgrade auf 3.1.1 die ich dann ohne Umwege über RaspberryMatic machen kann. 

Freundliche Grüße
Stefan 


©sblogoshs (2019)

**Comment by hobbyquaker** [comment]
Du kannst eine bestimmte Version von node-red-contrib-ccu installieren indem Du Dich auf der CCU per SSH einloggst und folgende Befehle ausführst: (Beispiel mit Version 3.1.2)
```
source /usr/local/addons/redmatic/home/.profile
cd /usr/local/addons/redmatic/var
npm install --save --no-package-lock --global-style --save-prefix="~" --production node-red-contrib-ccu@3.1.2
/etc/config/rc.d/redmatic restart
```

Genauso kannst dann auch wieder zurück auf die 3.1.1 gehen.

**Comment by sblogoshs21** [comment]
Okay, das ist machbar, aber erst Freitag oder Samstag. 

Gruß Stefan



©sblogoshs (2019)

**Comment by sblogoshs21** [comment]
Hallo. 

Ich hoffe das war’s wert, denn nun habe ich nach der Installation von 3.1.1 auch keine sysvar mehr. Im Anhang die log-Datei und ein Screenshot. 

In RedMatic wird die 3.1.1 zwar korrekt angezeigt und nun hoffe ich das es über den Umweg der RedMatic 5.2.0 wieder funktioniert, bisher hat es von der 5.2.1 und der 5.2.2 jedenfalls funktioniert, die 5.2.3 habe ich dann erst gar nicht mehr installiert. 

Gruß Stefan 





©sblogoshs (2019)

**Comment by sblogoshs21** [comment]
Hallo. 

Hat zum Glück funktioniert, ist wieder so etwas das nur schwer zu verstehen ist, es gibt doch bestimmt nur ein Version von 3.1.1 ! Natürlich bin ich froh das es geklappt hat weil ich den Frei(tag) anders verbringen möchte als mit „Probleme lösen“.

Gruß Stefan



©sblogoshs (2019)

**Comment by hobbyquaker** [comment]
@sblogoshs21 ich hab leider kein Log erhalten, ich glaube wenn Du per Email auf den Issue antwortest verwirft Github die Anhänge... Müsstest noch mal hier über die Github Webseite ranhängen.

**Comment by sblogoshs21** [comment]
Hallo.

Hier kommen die Dateien vom 06.12.
Gruß Stefan

[redmatic.2019-12-06T08_29_15.593Z.log](https://github.com/rdmtc/node-red-contrib-ccu/files/3962733/redmatic.2019-12-06T08_29_15.593Z.log)
![image0](https://user-images.githubusercontent.com/58234180/70832574-bdfeb200-1df5-11ea-8c42-a658326c3928.jpeg)

**Comment by hobbyquaker** [comment]
Kannst Du mir mal den Inhalt der Datei `/tmp/variables.rega.failed.json` zeigen? (Kannst z.B. mit Filezilla oder WinSCP von der CCU holen, dafür muss SSH in den CCU Einstellungen aktiviert sein)

**Comment by sblogoshs21** [comment]
Hallo. 

Ich habe in tmp keine solche Datei. 

Gruß Stefan



©sblogoshs (2019)



> Am 13.12.2019 um 23:53 schrieb Sebastian Raff <notifications@github.com>:
> 
> /tmp/variables.rega.failed.json

**Comment by sblogoshs21** [comment]
Schöne Feiertage!

Version 3.1.3 gesehen, aktualisiert, getestet und für **gut** befunden. 

Vielen Dank
Gruß Stefan
