### ISSUE TITLE
Lack "ccu-connection" node.

### ISSUE THREAD

**Issue by Plazmin** [rdmtc/node-red-contrib-ccu#109]
![ccu](https://user-images.githubusercontent.com/62091912/77066608-c1509d80-69e3-11ea-8b0e-0892b4a27a36.png)
![ccu1](https://user-images.githubusercontent.com/62091912/77066831-26a48e80-69e4-11ea-89cd-fb163971741e.png)
![ccu2](https://user-images.githubusercontent.com/62091912/77067128-bf3b0e80-69e4-11ea-96db-44f6d3dc1157.png)

**Comment by Plazmin** [comment]
I found a solution, my mistake.

**Comment by tsjensen** [comment]
@Plazmin I have the same problem. Can you share your solution?
