### ISSUE TITLE
rpc-Node rssiInfo

### ISSUE THREAD

**Issue by Bono1969** [rdmtc/node-red-contrib-ccu#122]
Der rpc Node liefert keine Werte bei rssiInfo zurück.
Getestet mit den letzten 6 Versionen (inkl. Beta) von RaspberryMatic auf einem Charly (RPi3).
Getestet mit Redmatic Version 5.5.2 (CCU Palette 3.1.4), Version 5.5.3 (CCU Palette 3.1.4) und Version 5.5.3 mit CCU Palette 3.2.0
![0664D717-7622-4164-9A9A-82F347FE126D](https://user-images.githubusercontent.com/37637519/85952563-6e836c00-b96a-11ea-9dcd-4ffe0cff5cd7.png)

**Comment by hobbyquaker** [comment]
@Bono1969 Habe eben versucht das zu reproduzieren, bei mir funktioniert es. Besteht das Problem bei Dir noch?
