### ISSUE TITLE
 UnhandledPromiseRejectionWarning: TypeError: done is not a function

### ISSUE THREAD

**Issue by richardabendroth** [rdmtc/node-red-contrib-ccu#123]
The following Error keeps flooding /var/log/messages

Jul 23 16:39:49 ccu3-webui daemon.err node-red: (node:663) UnhandledPromiseRejectionWarning: TypeError: done is not a function
Jul 23 16:39:49 ccu3-webui daemon.err node-red:     at ccu.methodCall.then.catch.error (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/nodes/ccu-rpc.js:61:25)
Jul 23 16:39:49 ccu3-webui daemon.err node-red:     at <anonymous>
Jul 23 16:39:49 ccu3-webui daemon.err node-red:     at process._tickCallback (internal/process/next_tick.js:189:7)
Jul 23 16:39:49 ccu3-webui daemon.err node-red: (node:663) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 74278)

**Comment by hmwelsch** [comment]
Look like similar problem here:
(node:19974) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'finished' of undefined
    at /home/pi/.node-red/node_modules/node-red-contrib-tahoma/dist/nodes/tahoma.js:105:42
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:19974) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 50)
(node:19974) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:19974) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'finished' of undefined
    at /home/pi/.node-red/node_modules/node-red-contrib-tahoma/dist/nodes/tahoma.js:105:42
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:19974) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 51)
(node:19974) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'finished' of undefined
    at /home/pi/.node-red/node_modules/node-red-contrib-tahoma/dist/nodes/tahoma.js:105:42
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:19974) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 52)
24 Jul 06:52:17 - [warn] Fehler beim Senden der Kommunikation: Error: WebSocket is not open: readyState 3 (CLOSED)

**Comment by hobbyquaker** [comment]
> UnhandledPromiseRejectionWarning: TypeError: done is not a function

@richardabendroth Which version of Node-RED are you using? node-red-contrib-ccu needs Node-RED >= 1.0

> UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'finished' of undefined
at /home/pi/.node-red/node_modules/node-red-contrib-tahoma/dist/nodes/tahoma.js:105:42

@hmwelsch This is unrelated. Most likely a bug in node-red-contrib-tahoma.
