### ISSUE TITLE
change config of ccu devices

### ISSUE THREAD

**Issue by konne** [rdmtc/node-red-contrib-ccu#142]
Hi,

I can wonderful get datapoints or change for example the current level of the light.
I the homeatic ccu i can for example define the light level for an on in % as the
configuration.

I there any way to set this level from node-red with your nodes?
For example I like to make change the config add daytime to 100% and in nighttime to 50%

bye

**Comment by Sineos** [comment]
Not tested and verified:

Most like you can do this via the `putParamset` method. With `getParamset` you can read out, which sets are support by your device and with `putParamset` you can modify them.

Below a simple example (sets the "Wochenprogramm" of a Thermostat):

`[{"id":"4c3d28a7.e0b42","type":"ccu-rpc","z":"427fc89b.e34038","name":"","ccuConfig":"38263145.35ea0e","iface":"BidCos-RF","method":"putParamset","params":"[\"LEQ0592683\", \"MASTER\", {\"WEEK_PROGRAM_POINTER\":2}]","topic":"${CCU}/${Interface}/${Method}","x":310,"y":480,"wires":[[]]},{"id":"919a6822.07f8d8","type":"debug","z":"427fc89b.e34038","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":470,"y":500,"wires":[]},{"id":"13092ff9.6b122","type":"inject","z":"427fc89b.e34038","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":110,"y":480,"wires":[["4c3d28a7.e0b42","6a0cbb2.b959044"]]},{"id":"6a0cbb2.b959044","type":"ccu-rpc","z":"427fc89b.e34038","name":"","ccuConfig":"38263145.35ea0e","iface":"BidCos-RF","method":"getParamset","params":"[\"LEQ0592683\", \"MASTER\"]","topic":"${CCU}/${Interface}/${Method}","x":310,"y":540,"wires":[["919a6822.07f8d8"]]},{"id":"38263145.35ea0e","type":"ccu-connection","name":"localhost","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":false,"cuxdEnabled":false,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"192.168.178.18","rpcServerHost":"192.168.178.18","rpcBinPort":"2047","rpcXmlPort":"2048","queueTimeout":"5000","queuePause":"250","contextStore":"default"}]`

**Comment by konne** [comment]
@Sineos thank you very much. This helped me a lot.
