### ISSUE TITLE
HmIP-BROLL Tasterkanäle lösen nicht aus

### ISSUE THREAD

**Issue by jokakilla** [rdmtc/node-red-contrib-ccu#153]
Für ein bestimmtes Programm möchte ich das Standardverhalten der Taster am Rolladen aktor ändern. Ich habe in der CCU die Direktverknüpfung entfernt und in meinem Flow einen ccu-value Block mit dem Channel des passenden HmIP-BROLL eingerichtet. Der Datenpunkt ist PRESS_SHORT.
Weder Kanal 1 noch Kanal 2 liefern beim Tippen der Wippe ein Event.
Den Rolladenstatus über Kanal 3 kommt und die Position über Kanal 4 lässt sich setzen. 

![grafik](https://user-images.githubusercontent.com/18099752/118287783-13039380-b4d4-11eb-8b76-d7c35a973317.png)
![grafik](https://user-images.githubusercontent.com/18099752/118287978-42b29b80-b4d4-11eb-99d1-9d61ee08eb45.png)

Mit dem Haken bei "Beim Start letzten bekannten Wert ausgeben" liefert der Node nach dem deploy einmal eine Nachricht mit Payload false aus. Aber weiterhin kommt kein Event beim Press.

Redmatic 7.2.1
node-red-contrib-ccu 3.4.2
Homematic 3.57.5
HmIP-BROLL 1.8.20

Bin für jede Hilfe dankbar!

**Comment by Sineos** [comment]
Vielleicht hilft: https://github.com/rdmtc/RedMatic/wiki/Faq#hmip---tastendruck-erzeugt-keine-events

**Comment by jokakilla** [comment]
Oha. Ja das hat geholfen. Danke für die schnelle Hilfe. Muss wohl nochmal an meinen Google Skills feilen ;)

**Comment by x2on** [comment]
Ich habe das gleiche Problem. Habe ein Dummy Programm für den HMIP-ROLL angelegt, leider hat das nichts gebracht. Noch Ideen?

**Comment by jokakilla** [comment]
Spontan leider nein. Bei mir läuft es wie beschrieben seit dem.
Einziges Problem: Alle paar Wochen/Monate steigt bei einzelnen Tastern die Funktion aus. Manchmal nur in eine Richtung manchmal auch in beide. Über andere Trigger als die Taster lässt sich der Rolladen aber noch normal fahren. Es hilft dann nur die Sicherung an der der HmIP-BROLL dran hängt kurz aus zu schalten.

**Comment by x2on** [comment]
Hm komisch. Mir ist noch ausgefallen das der HmIP-BROLL automatisch direkte Verknüpfungen zwischen Kanal 1/2 und 4 erstellt hat.

Ist das bei dir auch so?

**Comment by jokakilla** [comment]
Das ist wohl Standard und die müsste ich erstmal entfernen weil ich mich in das Verhalten einklinken wollte.

**Comment by x2on** [comment]
D.h. du hast die gelöscht?

**Comment by jokakilla** [comment]
Ja ich habe die gelöscht. Für mich war es sinnvoll die Standard Verknüpfungen zu löschen weil ich beim Antippen der Taster nicht automatisch ganz auf/zu fahren will. Bei mir ist es so dass die Fenster einen Zigbee Kontakt haben und wenn das Fenster offen ist fährt der Rolladen nur so weit zu dass noch ein paar Schlitzen zum lüften bleiben. Ob das immer notwendig oder für Deinen Einsatzzweck sinnvoll ist kann ich nicht sagen.
