### ISSUE TITLE
Keine Verbindung mit zu debmatic

### ISSUE THREAD

**Issue by Der-Schubi** [rdmtc/node-red-contrib-ccu#157]
Hallo!

Ich bin gerade von RaspberryMatic auf debmatic umgestiegen.
Meine debmatic Istallation läuft auf Debian Buster als virtuelle Maschine (qemu) unter proxmox.
So weit funktioniert alles, die Gerätekommunikation ist ok.

Nun komme ich leider mit Node-Red nicht auf die CCU. Erst hatte ich Node-Red auf einem lxc Container laufen, da aber keine Verbindung zustande kam, habe ich Node-Red jetzt direkt in der VM von debmatic mit drin. Ergebnis ist jeweils das gleiche.

Einstellungen für den ccu-connection node:
CCU address: 10.0.0.5
Listen address: 10.0.0.6 (bzw. .5 bei lokalem Node-Red)
Init address: 10.0.0.6 (dito ^^)
BINRPC listening port: 2000
XMLRPC listening port: 2001 (oder ist 2010 richtig?)
Angehakt sind ReGaHSS, BidCos-RF, HmIP-RF, VirtualDevices und CUxD
Authentifictation ist an und Username und Passwort korrekt gesetzt.

Startup von Node-Red:
[info] Node-RED version: v2.1.3
[info] Node.js  version: v12.22.5
[info] Linux 5.11.22-4-pve x64 LE
[info] Loading palette nodes
[info] node-red-contrib-ccu version: 3.4.2
[info] Dashboard version 3.1.0 started at /ui
[info] Settings file  : /home/schubi/.node-red/settings.js
[info] Context store  : 'default' [module=memory]
[info] User directory : /home/schubi/.node-red
[info] Server now running at http://127.0.0.1:1880/
[info] Flows file     : /home/schubi/.node-red/projects/Homeautomation/flow.json
[info] Starting flows
[info] [ccu-connection:3014F711A061A7D7098E1C89] paramsets loaded from /home/schubi/.node-red/paramsets.json
[warn] [ccu-connection:3014F711A061A7D7098E1C89] metadata new empty
[info] [ccu-connection:3014F711A061A7D7098E1C89] regadata loaded from /home/schubi/.node-red/ccu_rega_10.0.0.5 3014F711A061A7D7098E1C89.json
[info] [ccu-connection:3014F711A061A7D7098E1C89] values loaded from /home/schubi/.node-red/ccu_values_10.0.0.5 3014F711A061A7D7098E1C89.json
[error] [ccu-connection:38263145.35ea0e] Error: Invalid property expression: unexpected ' ' at position 12
[info] Started flows
[info] [mqtt-broker:ServDroid] Connected to broker: mqtt://10.0.0.3:1883

Woran kann es liegen?

Grüße,
Schubi

**Comment by Sineos** [comment]
Siehe https://github.com/rdmtc/node-red-contrib-ccu/blob/master/README.md

**Comment by Der-Schubi** [comment]
Das habe ich schon durchgearbeitet. Laut alexreinert nutzt debmatic die Ports 2000, 2001 und 2010. Das hat mich etwas verwirrt, aber bei dem Link ist das ja erklärt. Die Ports 1048/2049 habe ich auch durchprobiert. Die Firewall von Proxmox sowie die des Debian-Containers sind deaktiviert bzw. nicht vorhanden. Auf der Web-UI der CCU habe ich keinen Button zum Einstellen der Firewall, also gehe ich mal davon aus, dass debmatic keine hat.
Irgendwo stehe ich am Schlauch...

**Comment by Sineos** [comment]
Die verwendeten Ports müssen beim Starten des Container durchgereicht werden:

![grafik](https://user-images.githubusercontent.com/4459312/139674914-873e1cc7-3654-4b3c-99cf-494062600dfa.png)


Docker mit `-p 2048:2048 -p 2049:2049` starten

**Comment by Der-Schubi** [comment]
Nein, das geht bei LXC auch so. Ich nutze bridged networking. Unabhängig davon, müsste es ja mit einer lokalen Node-Red installation auf ein und dem selben Host wie die debmatic funkdionieren. Ich habe die Enistellungen so gesetzt wie in obigem Link beschrieben.

**Comment by Sineos** [comment]
Wenn Redmatic und Debmatic in der gleichen VM Instanz laufen dann ist:
* CCU Address: 127.0.0.1 oder localhost
* Listen Address: IP der Instanz
* Init Address: IP der Instanz

Wenn Debmatic und Redmatic in unterschiedlichen Instanzen laufen dann ist:
* CCU Address: IP der Debmatic Instanz
* Listen Address: IP der Node-Red Instanz
* Init Address: IP des Hosts

Edit:
Firewall der CCU natürlich auf aus und ggf. Port Forwarding beachten

**Comment by Der-Schubi** [comment]
Das habe ich alles so getestet. Unsicher bin ich mir bei dem fehlenden Button für die Firewall in der Systemsteuerung der CCU.

**Comment by Der-Schubi** [comment]
Ich habe den Fehler, ohne ihn wirklich gefunden zu haben, beseitigen können. Ich habe die debmatic noch einmal resettet und die Daten aus der Raspberrymatic neu importiert. Danach funktionierte es auf Anhieb.
Danke für die Hilfe und entschuldigung, dass ich hier die Hühner scheu gemacht habe.

Grüße,
Schubi
