### ISSUE TITLE
Missing values in Global Variable

### ISSUE THREAD

**Issue by multixz** [rdmtc/node-red-contrib-ccu#163]
When I start nodered over Docker and I check the Global Variable where the values, sysvar and program from the ccu are stored. The device, deviceName, deviceType, channelType, datapointType etc. from my HmIP Devices are undefined. But when I start it localy than I have all values.

**Comment by just-grizzle** [comment]
I had a similar issue where some devices could not be found and managed with `node-red-contrib-ccu`. 
Did you set the "Init address" of the ccu-connection node to the IP address of your host running Docker? That solved it for me.

**Comment by multixz** [comment]
Thx Problem solved :)
