### ISSUE TITLE
Sysvar node resets CCU variable

### ISSUE THREAD

**Issue by Ladis23** [rdmtc/node-red-contrib-ccu#171]
Hello,
I am using the "sysvar" node to read s system variable from CCU3 every 30sec.
![image](https://user-images.githubusercontent.com/119928671/205897345-73e24e35-bdeb-4b19-8beb-4df373cb02a6.png)
The variable is set by a simple CCU program depending on eTRV valve position. If the valve is open more than 10% the variable is set to 1 otherwise is 0.  The progran is set to check the valve position every 20sec. 
![image](https://user-images.githubusercontent.com/119928671/205899574-74360757-fceb-4c4d-8b46-6619520d6d35.png)
 
The issue I'm having is that every time the sysvar node reads the variable it sets it to 0 in the CCU. Therefore the output to node red is always 0.
![image](https://user-images.githubusercontent.com/119928671/205900711-715ca054-d953-4361-a219-0fc1d7868b03.png)

Is this a bug or I am doing something wrong?
Thank you

**Comment by Ladis23** [comment]
Sorted - "sysvar" node doesn't need inject to read the ccu variable. 
![image](https://user-images.githubusercontent.com/119928671/205920057-7907ae1e-e4f6-44a1-a879-2d9edcbaf312.png)
This works fine :)

**Comment by andesse** [comment]
> Sorted - "sysvar" node doesn't need inject to read the ccu variable. 
> 
> ![image](https://user-images.githubusercontent.com/119928671/205920057-7907ae1e-e4f6-44a1-a879-2d9edcbaf312.png)
> 
> This works fine :)

Yes, if you inject anything in the node with an payload, the Var usually takes that value. As you figured already out, the var will almost instantly send the state when it changed. 

Gruß 
Andreas
