### ISSUE TITLE
new setValue node

### ISSUE THREAD

**Issue by hobbyquaker** [rdmtc/node-red-contrib-ccu#20]
filtering similar to the rpc event node, issue setValue commands on multiple receivers.

**Comment by Hypnos3** [comment]
Super! Bitte eine Filtermöglichkeit auf den value mit einbauen, so dass man nur Datenpunkte mit bestimmten Wert schaltet. Danke!

**Comment by hobbyquaker** [comment]
in node-red-contrib-ccu 1.5.0 mal der erste Versuch ;-)
Ein Filter auf Value gibts noch nicht, aber es werden nur Kanäle gesetzt deren aktueller Wert sich von dem zu setzenden Wert unterscheidet. Die Autovervollständigung buggt auch noch. Wenn Du testen möchtest kannst node-red-contrib-ccu einfach über den Palette-Manager updaten.

**Comment by Hypnos3** [comment]
Ich bin leider noch nicht zum Testen gekommen. Versuche ich am Wochenende.

**Comment by Hypnos3** [comment]
Bei folgender KKonstallation:
![screenshot 2018-09-21 at 00 00 48](https://user-images.githubusercontent.com/12692680/45849222-7e036900-bd31-11e8-8661-5e8f0682894a.png)

Hier wird versucht nicht nur Datenpunkte des Gewerkes "Licht" zu schalten, sondern sehr viele. Auch welche, die kein Gewerk zugeodnet haben.

**Comment by hobbyquaker** [comment]
Ouch, mein Fehler, hab die Filterung nach Gewerken schlicht vergessen :(
Sollte in node-red-contrib-ccu v1.6.8 gefixt sein.

**Comment by hobbyquaker** [comment]
@Hypnos3 Können wir den Issue eigtl zumachen, oder brauchst Du noch den Filter nach Value? (ich halte den für verzichtbar, aber wenn Du ihn Dir wünscht ist es auch keine große Sachen den noch einzubauen)

**Comment by Hypnos3** [comment]
Kann von mir aus geschlossen werden.
