### ISSUE TITLE
Stadalone NODE-RED Instance Possible?

### ISSUE THREAD

**Issue by 50l1d7r33** [rdmtc/node-red-contrib-ccu#28]
Hi,

is there a way to use this node with a Node Red Instance whitch are not running on the CCU or RaspberryMatic itself?

Thanks ^^

**Comment by Sineos** [comment]
You need to install https://github.com/hobbyquaker/node-red-contrib-ccu and configure the CCU connection to point to your relevant Homematic IP

**Comment by psi-4ward** [comment]
is this solved?

**Comment by Vermatic** [comment]
I am not the original poster of this question.
However I'd like to comment that - as @Sineos pointed out - it is absolutely possible to add _node-red-contrib-ccu_ to any running Node-RED installation and then make it connect to a CCU easily.

**Comment by psi-4ward** [comment]
Yes, see https://redmatic.de/nodes/ccu/ccu-connection.html#ccu-connection for some IP related things.
