### ISSUE TITLE
Error while trying to set STATE via MQTT

### ISSUE THREAD

**Issue by m4rc77** [rdmtc/node-red-contrib-ccu#36]
I am trying to switch from `hm2mqtt.js` to `node-red-contrib-ccu` ... but I am still facing some issues.

When I try to set a value e.g. `true` or `false` for example on topic `hm/set/Stehlampe_Atelier/STATE` to switch on the lamp i get errors from `node-red-contrib-ccu` in the debug tab of NodeRED. The console log from NodeRED does not point out any further details.

The errors i get are: 
```
11/24/2018, 3:24:06 PMnode: CCU2msg : string[77]
"unknown paramsetDescription BidCos-RF/HM-LC-Sw1-Pl-DN-R5/2.5/8//VALUES STATE"

11/24/2018, 3:24:06 PMnode: CCU2msg : string[54]
" < BidCos-RF setValue Error: XML-RPC fault: Failure"

11/24/2018, 3:24:06 PMnode: CCU2msg : string[87]
"rpc > BidCos-RF setValue ["MEQ1506813","STATE","false"] < Error: XML-RPC fault: Failure"
```
For your information the setup of `ccu-connection` node and the mqtt flow according to [CCU an MQTT anbinden](https://github.com/HM-RedMatic/RedMatic/wiki/Flow-MQTT) is in my opinion now correct, as i get the `hm/status/#` messages and i am also able to switch `Stehlampe Atelier` with a `ccu-value` node but not via mqtt.

Any ideas what could be wrong? 

The `//` in the error message `"unknown paramsetDescription BidCos-RF/HM-LC-Sw1-Pl-DN-R5/2.5/8//VALUES STATE"` looks a little bit strange to me ... is there missing something?

**My setup:**
- RasPi with NodeRED 0.19.5 and node-red-contrib-ccu 1.9.1
- CCU2 with Firmware 2.31.25 
- Stehlampe Atelier is a HM-LC-Sw1-Pl-DN-R5

**Comment by m4rc77** [comment]
OK, let me know if I can check/test/try/fix something. 

I guess that function `paramsetName(iface, device, paramset)` in class `CcuConnectionNode` in file `ccu-connection.js` is creating the `//`.

In my case I guess `paramsetName(..)` should return `BidCos-RF/HM-LC-Sw1-Pl-DN-R5/2.5/8/SWITCH/VALUES` instead of `BidCos-RF/HM-LC-Sw1-Pl-DN-R5/2.5/8//VALUES` as this key also exists in the `ccu_<IP>.json` file in nodeRED root dir. But I am not sure if this is correct as I do not have enough CCU/BidCos-RF know-how.

**Comment by hobbyquaker** [comment]
Looked into this, but I'm not able to reproduce it. So I can only do some speculation on what could go wrong: Have you possibly set the same name for the Device itself and the Channel (`Stehlampe_Atelier`)?

**Comment by hdiessner** [comment]
Hello, I am in the exact situation (interesting, that always some kind of "Stehlampe" has to serve as a testing object).
In my case, yes: Device AND Channel have / had the same name. 
So I renamed the Device to Stehlampe_D and Channel back to Stehlampe.
That did the trick!

**Comment by m4rc77** [comment]
**The cause of the problem was, that device (Gerät) and channel (Kanal) had the same names.** 
Now all my devices have the prefix 'Device' and thanks to this no conflict exists with the channel names. The system now works as expected. Thanks for your help.

My current setup is:
    RasPi with NodeRED 0.20.3 and node-red-contrib-ccu 2.0.5
    CCU2 with Firmware 2.41.9
    Test-Device: Stehlampe Atelier (HM-LC-Sw1-Pl-DN-R5, Device-Name: 'Device Stehlampe Atelier', Channel-Name: 'Stehlampe Atelier')

Thanks a lot for the great work!
