### ISSUE TITLE
MQTT status

### ISSUE THREAD

**Issue by taucher4000** [rdmtc/node-red-contrib-ccu#55]
Hi,

ich habe ein merkwürdiges Verhalten des CCU-MQTT Nodes festgestellt. Der topic status meiner Schalter (z.B. hm/status/Schaltsteckdose-Wohnzimmer-Sideboard/STATE) wird manchmal mit 1/ 0 und manchmal mit ON/OFF zurück gegeben. Leider kann ich dies nicht so richtig nachvollziehen oder reproduzieren.

Wie sollte der Status aussehen? Sollte dies eine Nummer (1 oder 0) oder ein String (ON oder OFF) sein?

Gruß
Taucher

**Comment by hobbyquaker** [comment]
Das kommt drauf an welches Payload Format Du gewählt hast. Bei "mqsh-extended" und "mqsh-basic" kommt `true` oder `false` raus.
So sieht so eine Nachricht (mit Payload "mqsh-extended") bei mir aus:
```
hm/status/Standby Fernseher/STATE {"val":true,"ts":1547279651539,"lc":1547279651539,"hm":{"ccu":"localhost","iface":"BidCos-Wired","device":"FEQ0062347","deviceName":"Schaltaktor EG 1","deviceType":"HMW-IO-12-Sw7-DR","channel":"FEQ0062347:16","channelName":"Standby Fernseher","channelType":"SWITCH","channelIndex":16,"datapoint":"STATE","datapointName":"BidCos-Wired.FEQ0062347:16.STATE","datapointType":"BOOL","datapointMin":false,"datapointMax":true,"datapointDefault":false,"datapointControl":"SWITCH.STATE","valuePrevious":false,"valueStable":true,"rooms":["Wohnzimmer"],"room":"Wohnzimmer","functions":["Standby"],"function":"Standby","ts":1547279651539,"tsPrevious":1547249183767,"lc":1547279651539,"change":true,"cache":false,"working":false,"stable":true}}
```
Wenn Du als Payload Format "Plain" gewählt hast kommt `0` und `1`.

`ON` oder `OFF` wird definitiv nicht von node-red-contrib-ccu erzeugt, die Zeichenketten kommen im Quelltext nirgends vor. Kann mir nicht erklären wie das zustande kommt. Hast Du den MQTT Node direkt mit einem MQTT Out Node verbunden oder verarbeitest Du die Nachrichten noch in zwischengeschalteten Nodes?
