### ISSUE TITLE
Keine Verbindung zu CCU2

### ISSUE THREAD

**Issue by MisterR72** [rdmtc/node-red-contrib-ccu#60]
Bei mir läuft eine Ccu2, ioBroker im Docker auf der Synology mit NodeRed.
Wenn ich nun Versuche die Node mit meiner Ccu2 zu verbinden bekomme ich keine Verbindung und komme dann auch nicht mehr auf den NodeRed Adapter, connection lost.
Auch das Auswahlfeld mit Bidcos-RF ist ausgegraut, kann nichts angewählt werden.
Die ports habe ich jeweile angepasst wie in den Homematic Adaptern.

Was kann ich noch tun?
Gruss Ralf

**Comment by emeins** [comment]
Läuft Node Red als ioBroker AddOn?
Hatte das gleiche Problem, siehe https://github.com/HM-RedMatic/RedMatic/issues/141
Wenn ich NodeRed standalone installiere, hat es funktioniert. Leider komme ich dann aber nicht an die ioBroker Daten ran.

**Comment by emeins** [comment]
Nein, nicht wirklich. Wie oben beschrieben, habe ich Node Red jetzt ohne ioBroker installiert, da läuft es ja. Ich habe auch noch mal einen Issue bei ioBroker.node-red aufgemacht, mal schauen, ob da was kommt.
https://github.com/ioBroker/ioBroker.node-red/issues/50

**Comment by MisterR72** [comment]
Ok, geht ja auch erstmal so. Evtl. kommt eh bald ne CCU3. Danke

**Comment by emeins** [comment]
Läuft jetzt nach Anpassung der Datei /opt/ioBroker/node_modules/iobroker.node-red/settings.js

Siehe: https://github.com/ioBroker/ioBroker.node-red/issues/50#issuecomment-460349393

**Comment by hobbyquaker** [comment]
https://github.com/rdmtc/node-red-contrib-ccu/commit/9f55e5fbc6d40ab6723ff44709c0587c524abff2
