### ISSUE TITLE
unknown paramsetDescription STATE with HM-MOD-Re-8 

### ISSUE THREAD

**Issue by ykoer** [rdmtc/node-red-contrib-ccu#66]
Hi,

I have RaspberryMatic which talks to an 8 channel Homematic receiver (HM-MOD-Re-8 ). I am seeing "unknown paramsetDescription STATE" in Node-Red when I try to set ON or OFF state on a given channel

XMLRPC port is set to 2000. Not sure about BINRPC though. Another weird thing is that I have to provide channel + datapoint again with each node edit.

Any ideas what I am doing wrong here?

Thanks
Yusuf

**Comment by hobbyquaker** [comment]
Are you using RedMatic or node-red-contrib-ccu with a "normal" Node-RED? Do you have other actuators that can be used without problems? Can you pls send me the file `ccu_paramsets_v2.json` to hobbyquaker@gmail.com?

**Comment by ykoer** [comment]
I am using node-red-contrib-ccu with normal Node-Red. No I don't have any other actuator than the 8-channel receiver module from ELV (https://www.elv.de/homematic-8-kanal-empfangsmodul.html)

I just mailed you the ccu_paramsets_v2.json file. 
Thanks for your support again.

**Comment by hobbyquaker** [comment]
Seems like the connection to the ccu is not working at all. Can you configure your Node-RED to log level debug and show me the log, especially the messages prefixed with "ccu-connection" are of relevance. It would also be helpful if you subscribe your environment (IP of the CCU, IP of the Host running Node-RED, eventual Container/Docker Addresses) and show me a screenshot of the ccu connection configuration.

**Comment by ykoer** [comment]
Hi @hobbyquaker ,

the connection to CCU is working and I can see the led connected to the Homematic device switching on or off.

Switch Off:
<img width="819" alt="Screen Shot 2019-03-18 at 16 46 54" src="https://user-images.githubusercontent.com/3517764/54543350-cb3d5c00-499d-11e9-9bd4-b691f1aea71e.png">
<img width="739" alt="Screen Shot 2019-03-18 at 16 46 00" src="https://user-images.githubusercontent.com/3517764/54543371-d5f7f100-499d-11e9-9bbe-2ab1d27d5e78.png">

Switch On:
<img width="811" alt="Screen Shot 2019-03-18 at 16 47 13" src="https://user-images.githubusercontent.com/3517764/54543418-ec9e4800-499d-11e9-81fe-ef4470caf721.png">
<img width="564" alt="Screen Shot 2019-03-18 at 16 47 26" src="https://user-images.githubusercontent.com/3517764/54543434-f32cbf80-499d-11e9-82e2-c6f2e59fd66a.png">

I am not sure what you mean with: subscribe your environment.
1) Node-Red instance is running locally on my MacBook Pro for testing only. IP: 192.168.178.47. I will move it into a Docker Container running on my Intel NUC, once everything works as expected
2) CCU (RaspberryMatic) is running on a Raspberry Pi 3 Model B+, IP: 192.168.178.66

And here are the Debug Logs from Node-ed

`
ykoer@ykoer-mac ~/.node-red $ node-red
18 Mar 16:41:37 - [info]

Welcome to Node-RED
===================

18 Mar 16:41:37 - [info] Node-RED version: v0.19.5
18 Mar 16:41:37 - [info] Node.js  version: v10.9.0
18 Mar 16:41:37 - [info] Darwin 18.2.0 x64 LE
18 Mar 16:41:37 - [info] Loading palette nodes
18 Mar 16:41:37 - [debug] Module: node-red-contrib-ccu 2.0.1
18 Mar 16:41:37 - [debug]         /Users/ykoer/.node-red/node_modules/node-red-contrib-ccu
18 Mar 16:41:37 - [debug] Module: node-red-contrib-ftp-sftp 1.8.8
18 Mar 16:41:37 - [debug]         /Users/ykoer/.node-red/node_modules/node-red-contrib-ftp-sftp
18 Mar 16:41:37 - [debug] Module: node-red-contrib-sftp 0.0.8
18 Mar 16:41:37 - [debug]         /Users/ykoer/.node-red/node_modules/node-red-contrib-sftp
18 Mar 16:41:37 - [debug] Module: node-red-node-email 0.1.29
18 Mar 16:41:37 - [debug]         /Users/ykoer/.nvm/versions/node/v10.9.0/lib/node_modules/node-red/node_modules/node-red-node-email
18 Mar 16:41:37 - [debug] Module: node-red-node-feedparser 0.1.14
18 Mar 16:41:37 - [debug]         /Users/ykoer/.nvm/versions/node/v10.9.0/lib/node_modules/node-red/node_modules/node-red-node-feedparser
18 Mar 16:41:37 - [debug] Module: node-red-node-rbe 0.2.4
18 Mar 16:41:37 - [debug]         /Users/ykoer/.nvm/versions/node/v10.9.0/lib/node_modules/node-red/node_modules/node-red-node-rbe
18 Mar 16:41:37 - [debug] Module: node-red-node-twitter 1.1.4
18 Mar 16:41:37 - [debug]         /Users/ykoer/.nvm/versions/node/v10.9.0/lib/node_modules/node-red/node_modules/node-red-node-twitter
18 Mar 16:41:38 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
18 Mar 16:41:38 - [info] node-red-contrib-ccu version: 2.0.1
18 Mar 16:41:38 - [info] Settings file  : /Users/ykoer/.node-red/settings.js
18 Mar 16:41:38 - [info] Context store  : 'default' [module=memory]
18 Mar 16:41:38 - [info] User directory : /Users/ykoer/.node-red
18 Mar 16:41:38 - [warn] Projects disabled : editorTheme.projects.enabled=false
18 Mar 16:41:38 - [info] Flows file     : /Users/ykoer/.node-red/flows_ykoer-mac.json
18 Mar 16:41:38 - [debug] loaded flow revision: 4ac77d252b220f82949622846d63c6ca
18 Mar 16:41:38 - [debug] red/runtime/nodes/credentials.load : no user key present
18 Mar 16:41:38 - [debug] red/runtime/nodes/credentials.load : using default key
18 Mar 16:41:38 - [debug] red/runtime/nodes/credentials.load : keyType=system
18 Mar 16:41:38 - [warn]

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

18 Mar 16:41:38 - [info] Starting flows
18 Mar 16:41:38 - [debug] red/nodes/flows.start : starting flow : global
18 Mar 16:41:38 - [debug] red/nodes/flows.start : starting flow : b020871f.a05678
[http://wwww.HardingPoint.com] SFTP - Config - hmac: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[http://wwww.HardingPoint.com] SFTP - Config - cipher: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm
[http://wwww.HardingPoint.com] SFTP - Using User/Pwd
18 Mar 16:41:38 - [debug] [ccu-connection:CCU] ccu-connection 192.168.178.66
18 Mar 16:41:38 - [info] [ccu-connection:CCU] paramsets loaded from /Users/ykoer/.node-red/paramsets.json
18 Mar 16:41:38 - [info] [ccu-connection:CCU] metadata new empty
18 Mar 16:41:38 - [debug] [ccu-connection:CCU] rpc client created BidCos-RF {"host":"192.168.178.66","port":2001,"headers":{"User-Agent":"NodeJS XML-RPC Client","Content-Type":"text/xml","Accept":"text/xml","Accept-Charset":"UTF8","Connection":"Keep-Alive"},"method":"POST"}
18 Mar 16:41:38 - [info] [ccu-connection:CCU] Interfaces: BidCos-RF
this.ftpConfig: {"id":"64db7005.26117","type":"ftp","z":"","_closeCallbacks":[],"wires":[],"_wireCount":0,"options":{"host":"test.rebex.net","port":21,"secure":false,"secureOptions":"","user":"demo","password":"password","pass":"password","connTimeout":10000,"pasvTimeout":10000,"keepalive":10000}}
18 Mar 16:41:38 - [info] Started flows
18 Mar 16:41:38 - [info] [ccu-connection:CCU] xmlrpc server listening on http://192.168.178.66:2000
18 Mar 16:41:38 - [info] [ccu-connection:CCU] init BidCos-RF http://192.168.178.66:2000 nr_HCckQE_BidCos-RF
18 Mar 16:41:38 - [debug] [ccu-connection:CCU] rpc > BidCos-RF init ["http://192.168.178.66:2000","nr_HCckQE_BidCos-RF"]
18 Mar 16:41:38 - [info] Server now running at http://127.0.0.1:1880/
18 Mar 16:41:38 - [debug] [ccu-connection:CCU]     < BidCos-RF init ""
18 Mar 16:41:38 - [debug] [ccu-connection:CCU] rpc > BidCos-RF getLinks []
18 Mar 16:41:39 - [debug] [ccu-connection:CCU]     < BidCos-RF getLinks []
18 Mar 16:41:39 - [info] [ccu-connection:CCU] BidCos-RF http port 2001 connected
18 Mar 16:42:38 - [debug] [ccu-connection:CCU] stats rpc rx: {} tx: {}
18 Mar 16:42:38 - [debug] [ccu-connection:CCU] stats rpc subscribers 1
18 Mar 16:42:38 - [debug] [ccu-connection:CCU] stats rega subscribers 0
18 Mar 16:43:00 - [warn] [ccu-connection:CCU] unknown paramsetDescription   STATE
18 Mar 16:43:00 - [debug] [ccu-connection:CCU] rpc > BidCos-RF setValue ["OEQ0206095:1","STATE","false"]
18 Mar 16:43:00 - [debug] [ccu-connection:CCU]     < BidCos-RF setValue ""
18 Mar 16:43:38 - [debug] [ccu-connection:CCU] stats rpc rx: {} tx: {"BidCos-RF":1}
18 Mar 16:43:38 - [debug] [ccu-connection:CCU] stats rpc subscribers 1
18 Mar 16:43:38 - [debug] [ccu-connection:CCU] stats rega subscribers 0
18 Mar 16:44:38 - [debug] [ccu-connection:CCU] stats rpc rx: {} tx: {"BidCos-RF":1}
18 Mar 16:44:38 - [debug] [ccu-connection:CCU] stats rpc subscribers 1
18 Mar 16:44:38 - [debug] [ccu-connection:CCU] stats rega subscribers 0
18 Mar 16:45:38 - [debug] [ccu-connection:CCU] stats rpc rx: {} tx: {"BidCos-RF":1}
18 Mar 16:45:38 - [debug] [ccu-connection:CCU] stats rpc subscribers 1
18 Mar 16:45:38 - [debug] [ccu-connection:CCU] stats rega subscribers 0
18 Mar 16:46:38 - [debug] [ccu-connection:CCU] stats rpc rx: {} tx: {"BidCos-RF":1}
18 Mar 16:46:38 - [debug] [ccu-connection:CCU] stats rpc subscribers 1
18 Mar 16:46:38 - [debug] [ccu-connection:CCU] stats rega subscribers 0
18 Mar 16:46:59 - [warn] [ccu-connection:CCU] unknown paramsetDescription   STATE
18 Mar 16:46:59 - [debug] [ccu-connection:CCU] rpc > BidCos-RF setValue ["OEQ0206095:1","STATE","true"]
18 Mar 16:47:00 - [debug] [ccu-connection:CCU]     < BidCos-RF setValue ""
18 Mar 16:47:38 - [debug] [ccu-connection:CCU] stats rpc rx: {} tx: {"BidCos-RF":2}
18 Mar 16:47:38 - [debug] [ccu-connection:CCU] stats rpc subscribers 1
18 Mar 16:47:38 - [debug] [ccu-connection:CCU] stats rega subscribers 0
18 Mar 16:48:38 - [debug] [ccu-connection:CCU] stats rpc rx: {} tx: {"BidCos-RF":2}
18 Mar 16:48:38 - [debug] [ccu-connection:CCU] stats rpc subscribers 1
18 Mar 16:48:38 - [debug] [ccu-connection:CCU] stats rega subscribers 0
18 Mar 16:49:38 - [debug] [ccu-connection:CCU] stats rpc rx: {} tx: {"BidCos-RF":2}
18 Mar 16:49:38 - [debug] [ccu-connection:CCU] stats rpc subscribers 1
18 Mar 16:49:38 - [debug] [ccu-connection:CCU] stats rega subscribers 0
18 Mar 16:50:38 - [debug] [ccu-connection:CCU] stats rpc rx: {} tx: {"BidCos-RF":2}
18 Mar 16:50:38 - [debug] [ccu-connection:CCU] stats rpc subscribers 1
18 Mar 16:50:38 - [debug] [ccu-connection:CCU] stats rega subscribers 0
`

**Comment by hobbyquaker** [comment]
Please check if the CCU Firewall allows connections to Port 2001/2010/9292/8181 (for testing just try to set it to "ports open"). Also check if "Authentication" is active in your CCU security settings, this has to be turned off, it's not (yet) supported by node-red-contrib-ccu.

**Comment by ykoer** [comment]
sure take your time @hobbyquaker

**Comment by ykoer** [comment]
@hobbyquaker I just played around with the ccu node and could resolve the issue. 
It was the Listen Address. It doesn't somehow work with "0.0.0.0". I had to select the IP address of the server.
Now I see a file ccu_192.168.178.66.json and the node has a drop down with the available channels and datapoints.
