### ISSUE TITLE
cannot connect to ccu since last update

### ISSUE THREAD

**Issue by EdgarM73** [rdmtc/node-red-contrib-ccu#68]
Hi there,

i have updated to node-red 0.20 yesterday and everything worked fine. today I have updated the ccu plugin, and the connection cannot be established anymore.

Logfile says:

[ccu-connection:CCU] unknown paramsetDescription  BidCos-RF/HM-CC-RT-DN/1.5/29/CLIMATECONTROL_RT_TRANSCEIVER/VALUES SET_TEMPERATURE

anyone can give me a hint what is wrong.

Also the nodes are all showing disconnected.

I have nodered in an Docker Container and it used to work fine until today.

regards

**Comment by hobbyquaker** [comment]
Please double check your ccu-connection configuration (see https://github.com/rdmtc/node-red-contrib-ccu/blob/master/README.md#Configuration-Examples)

**Comment by hobbyquaker** [comment]
Which Node.js Version do you use? node-red-contrib-ccu requires >=10.0.0

**Comment by hobbyquaker** [comment]
node-red-contrib-ccu v2.0.6 is node 8 compatible again
