### ISSUE TITLE
Verbindung zu CCU2 von standalone-node-red nicht möglich

### ISSUE THREAD

**Issue by mrc007** [rdmtc/node-red-contrib-ccu#69]
Umgebung: CCU2, VM mit Ubuntu 18.04.2 LTS mit node.js 8.10.0 und node-red 0.20.0 und node-red-contrib-ccu 2.0.1
Mir gelingt es leider nicht den CCU-Node gegen eine CCU2 vollständig zu verbinden.
Wenn die Interfaces RegaHSS und die beiden RF-Interfaces gleichzeitig im ccu-connection-Knoten angehakt sind, verbinden sich nur die RegaHSS-Knoten. Die RPC-Knoten bleiben disconnected.
Beim Testen habe ich dann folgendes herausgefunden:
Wenn ich nur die RF-Interfaces aktiviere, und RegaHSS-Interface deaktiviere, verbinden sich die RPC-Knoten (connected) und die Rega-Knoten gehen auf disconnected.
Und zur Vollständigkeit: Wenn ich nur das RegaHSS-Interface im ccu-connection-Knoten aktiviere, wechseln die Rega-Knoten auf connected, die RPC-Knoten bleiben disconnected.

Wenn die RPC-Knoten nicht connected sind, gibt es auch keinen offenen Port im listening-Zustand.

Wo kann ich noch suchen woran es liegen könnte? Im Syslog steht auch nichts hilfreiches. Woran könnte das liegen? Ist die nodejs-Version zu alt?

**Comment by hobbyquaker** [comment]
Beschreib mal bitte Deine Umgebung (VM Netzwerk Bridged? IP, IP der CCU) und zeig ein Screenshot des ccu-connection Nodes.

**Comment by mrc007** [comment]
Aufbau ist ganz einfach: VM ist bridged angebunden. CCU und Node Red VM sind also im selben Subnetz.
CCU 192.168.169.30
Node Red VM 192.168.169.159
![AA6E277D-53BD-4854-91A8-D8BCB9E7FEA3](https://user-images.githubusercontent.com/48654255/54562600-a1009400-49c7-11e9-871a-363cb491efa8.jpeg)

**Comment by hobbyquaker** [comment]
Hab eben beim anschauen des Logs von #70 bemerkt dass ich auf eine Funktion (Promise.finally) zurückgegriffen hab die erst ab Node >= 10.0.0 zur Verfügung steht. War mir nicht bewussst, bin auch nicht ganz happy damit da Node 8 noch im LTS ist, aber vorerst wird Dir da nichts anderes bleiben als Nodejs zu aktualisieren.

**Comment by mrc007** [comment]
Danke für deine Rückmeldung. Ja das war mein Plan gewesen, möglichst viel aus Paketquellen der Distribution zu nutzen... Dann mache ich mich in den nächsten Tagen an die Umsetzung mit Nodejs10 und gebe dann nochmal Rückmeldung ob es läuft - wovon auszugehen ist.

**Comment by hobbyquaker** [comment]
node-red-contrib-ccu v2.0.6 is node 8 compatible again
