### ISSUE TITLE
[node-red-contrib-ccu/ccu-connection] SyntaxError: Unexpected token ... "Waiting for missing types to be registered"

### ISSUE THREAD

**Issue by GQuan42** [rdmtc/node-red-contrib-ccu#72]
Hi,

I'm running NodeRed on a Pi3 with Node-Red-Contrib-CCU.

Node-Red-Version v0.20.3
Node.js v8.1.3
Contrib-CCU 2.0.5

Whenever I try to use a Homematic node and use the configuration node, NodeRed start telling me 

29 Mar 11:38:51 - [info] Waiting for missing types to be registered:
29 Mar 11:38:51 - [info]  - ccu-connection

During startup of NodeRed I receive the following message:

29 Mar 11:35:11 - [warn] ------------------------------------------------------
29 Mar 11:35:11 - [warn] [node-red-contrib-ccu/ccu-connection] SyntaxError: Unexpected token ...
29 Mar 11:35:11 - [warn] ------------------------------------------------------

Any ideas?

**Comment by hobbyquaker** [comment]
same root cause as in #68 and #69 - node-red-contrib-ccu needs Node.js >= v10.0.0

**Comment by GQuan42** [comment]
Thanks a lot for the information.

But now I'm struggeling: How do I update Node.JS which seems to be part of the docker image?

Any help welcome :-)

**Comment by hobbyquaker** [comment]
node-red-contrib-ccu v2.0.6 is node 8 compatible again

**Comment by GQuan42** [comment]
Hi,
sorry, but I wasn't able to test this earlier.
I uninstalled the old package, installed version 2.0.6, but I'm still getting the same messages: 

3 Apr 07:11:04 - [info] Added node types:
3 Apr 07:11:04 - [info]  - node-red-contrib-ccu:ccu-connection : SyntaxError: Unexpected token ...
3 Apr 07:11:04 - [info]  - node-red-contrib-ccu:ccu-value
3 Apr 07:11:04 - [info]  - node-red-contrib-ccu:ccu-rpc-event
3 Apr 07:11:04 - [info]  - node-red-contrib-ccu:ccu-set-value
3 Apr 07:11:04 - [info]  - node-red-contrib-ccu:ccu-rpc
3 Apr 07:11:04 - [info]  - node-red-contrib-ccu:ccu-signal
3 Apr 07:11:04 - [info]  - node-red-contrib-ccu:ccu-display
3 Apr 07:11:04 - [info]  - node-red-contrib-ccu:ccu-sysvar
3 Apr 07:11:04 - [info]  - node-red-contrib-ccu:ccu-program
3 Apr 07:11:04 - [info]  - node-red-contrib-ccu:ccu-script
3 Apr 07:11:04 - [info]  - node-red-contrib-ccu:ccu-poll
3 Apr 07:11:04 - [info]  - node-red-contrib-ccu:ccu-get-value
3 Apr 07:11:04 - [info]  - node-red-contrib-ccu:ccu-switch
3 Apr 07:11:04 - [info]  - node-red-contrib-ccu:ccu-mqtt

**Comment by baxerus** [comment]
Same for me made updates of everything (some hours ago).
* node-red-contrib-ccu version: 2.0.7

**Comment by hobbyquaker** [comment]
2.0.8 and higher are compatible with node 8 again.
