### ISSUE TITLE
Locking window with Winmatic

### ISSUE THREAD

**Issue by chrispi68** [rdmtc/node-red-contrib-ccu#74]
I am using the MQTT node. When I set the "Level" of my Winmatic to "-0.005" the window should close and also should be locked. But instead, the level ist set to "0", which means the window is unlocked.

**Comment by hobbyquaker** [comment]
Could you create a Log on level Debug that shows that behavior?

**Comment by hobbyquaker** [comment]
Related: https://homematic-forum.de/forum/viewtopic.php?f=77&t=50106&p=503528#p503528

**Comment by hobbyquaker** [comment]
Can you pls try if it works with node-red-contrib-ccu version 2.0.9?

**Comment by chrispi68** [comment]
Sure, but how can I upgrade to version 2.0.9? NodeRed only shows version 2.0.8.

**Comment by hobbyquaker** [comment]
sry, my bad. Now it should be available :)

**Comment by chrispi68** [comment]
Hmm, I just did a restart of my CCU but still only 2.0.8.

**Comment by hobbyquaker** [comment]
hmm... i guess the node red package registry needs a while for syncing from npmjs.com
Just try again later.

**Comment by chrispi68** [comment]
Ok.

**Comment by chrispi68** [comment]
I just tried version 2.0.9 and locking (value -0.005) is now woking.

Thank you very much!
