### ISSUE TITLE
Even with 2.0.7: [node-red-contrib-ccu/ccu-connection] SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by baxerus** [rdmtc/node-red-contrib-ccu#75]
I made an update of `node-red-contrib-ccu` to 2.0.6 today and it wasn't working anymore with `[warn] [node-red-contrib-ccu/ccu-connection] SyntaxError: Unexpected token ....``` on the console.

I searched the issues and found that I could have something to do with my Node.js version so I updated my node-red docker container also (`nodered/node-red-docker:rpi` pulled also some hours ago). Still not working with the same error.

In the meantime the `node-red-contrib-ccu` version 2.0.7 was released ❤️. So I tried it full of hope, but still not working ☹️.

Now my versions are like this:
* node-red-contrib-ccu version: 2.0.7
* Node-RED version: v0.20.5
* Node.js version: v8.1.3
but the error message is still the same: `8 Apr 19:48:07 - [warn] [node-red-contrib-ccu/ccu-connection] SyntaxError: Unexpected token ....`

Is it possible, that the polyfill doesn't work?

**Comment by baxerus** [comment]
Update:

I build myself a docker container that uses Node.js version v10.15.3 and it is working in this container. As assumed already it seems like a Node.js 8 problem. Probably the polyfill isn't working perfectly (or more has to be polyfilled).

I'm sorry that there is no more logging output after the `Unexpected token ....`, probably the problematic line would come next. I tried for an hour or so to get longer/better error output, but wasn't able to get it (and than I stopped, after realizing how much I was of track already). Do you have an idea, how I could get more error output in node-red? Than I would add it here.

**Comment by hobbyquaker** [comment]
I'm quite optimistic that 2.0.8 now works with Node 8 again.

**Comment by baxerus** [comment]
Yes! 😍 Version 2.0.8 working with Node 8.1.3 (at least for me). Tested with the docker hub version of `nodered/node-red-docker:rpi`

Thank you for the very fast fix! 👍
