### ISSUE TITLE
MQTT retain messages

### ISSUE THREAD

**Issue by Markus-** [rdmtc/node-red-contrib-ccu#79]
Hallo,

ich wollte auf diesem Wege erfahren wann eine Nachricht mit retain: true geschickt wird und wann nicht. Wenn ich das Topic hm/status/REED-KONTAKT-XY abonniere, sehe ich im Debugging-Fenster das Flag als "false" gesetzt. 

Schaue ich auf den Broker wurde aber wohl irgendwann mal eine Nachricht des Kontakts mit retain: true geschickt.

Gibt es da eine Doku / Regel zu?

Gruß
Markus

**Comment by hobbyquaker** [comment]
https://github.com/rdmtc/node-red-contrib-ccu/blob/master/nodes/ccu-mqtt.js#L94 - `retain` wird grundsätzlich gesetzt - außer für "One Shot Events", also sowas wie `PRESS_SHORT`, `PRESS_CONT`, ...

**Comment by hobbyquaker** [comment]
Ah und noch ein hinweis: Auch wenn mit `retain: true` published wird - als Subscriber steht da trotzdem `retain: false`. Ein Subscriber bekommt nur dann `retain: true` wenn er eine Nachricht bekommt die bereits früher mit retain gesendet wurde. Erhältst Du eine Nachricht "frisch" ist retain immer false.

**Comment by Markus-** [comment]
Ah, dass erklärt das Ganze. 

Wenn ich quasi node-red restarte habe ich retain: true weil die Verbindung zum Broker neu aufgebaut wird. Im Hintergrund "merkt" sich der Broker für künftige Neuanmeldungen den Status durch das retain: true - während ich angemeldet bin sehe ich jedoch retain: false.

Danke für die Klarstellung.

Gruß
Markus
