### ISSUE TITLE
Problem mit Version V2.1.3

### ISSUE THREAD

**Issue by Matten-Matten** [rdmtc/node-red-contrib-ccu#84]
ich hab mir eine Kette  gebaut dessen msg.xx immer anders heißt,
jetzt werden aber alle mit dem ersten wert überschrieben.
Warum?
![Node-RED _ 192 168 27 42-16 05 2019_01_23_16](https://user-images.githubusercontent.com/32074970/57815808-42625700-7779-11e9-9b94-b26490e0ced6.jpg)

wenn ich auf V2.0.15 downgrade funktioniert es wieder und es sieht wieder so aus:
![Node-RED _ 2 0 15](https://user-images.githubusercontent.com/32074970/57815708-cd8f1d00-7778-11e9-91d6-f77ac6bbf500.jpg)

`

`[{"id":"4f537b61.1a5894","type":"link in","z":"49b6d8c6.4cc838","name":"Nachricht vorbereiten","links":["fed0c90a.7a8ad8","714bfc6d.e68174"],"x":55,"y":340,"wires":[["af21a3a2.2588c"]]},{"id":"9ce8d5db.460e08","type":"ccu-get-value","z":"49b6d8c6.4cc838","name":"Text","ccuConfig":"38263145.35ea0e","iface":"ReGaHSS","channel":"","sysvar":"X_Pushover_Text","sysvarProperty":"value","datapoint":"","datapointProperty":"value","setProp":"payload","setPropType":"msg","x":330,"y":400,"wires":[["5cfe3627.364b78"]]},{"id":"af21a3a2.2588c","type":"ccu-get-value","z":"49b6d8c6.4cc838","name":"Betreff","ccuConfig":"38263145.35ea0e","iface":"ReGaHSS","channel":"","sysvar":"X_Pushover_Betreff","sysvarProperty":"value","datapoint":"","datapointProperty":"value","setProp":"topic","setPropType":"msg","x":190,"y":420,"wires":[["9ce8d5db.460e08"]]},{"id":"5cfe3627.364b78","type":"ccu-get-value","z":"49b6d8c6.4cc838","name":"Bild","ccuConfig":"38263145.35ea0e","iface":"ReGaHSS","channel":"","sysvar":"X_Pushover_Bild","sysvarProperty":"value","datapoint":"","datapointProperty":"value","setProp":"picture","setPropType":"msg","x":490,"y":340,"wires":[["efadbc3e.56e5a"]]},{"id":"efadbc3e.56e5a","type":"ccu-get-value","z":"49b6d8c6.4cc838","name":"person","ccuConfig":"38263145.35ea0e","iface":"ReGaHSS","channel":"","sysvar":"X_Pushover_Device","sysvarProperty":"value","datapoint":"","datapointProperty":"value","setProp":"person","setPropType":"msg","x":610,"y":340,"wires":[["acbe8bae.3ec428"]]},{"id":"acbe8bae.3ec428","type":"switch","z":"49b6d8c6.4cc838","name":"Person?","property":"person","propertyType":"msg","rules":[{"t":"true"},{"t":"false"}],"checkall":"false","repair":false,"outputs":2,"x":740,"y":340,"wires":[["d74b17f6.c819d8"],["ad006013.c7d91"]]},{"id":"38263145.35ea0e","type":"ccu-connection","z":"","name":"ccu","host":"127.0.0.1","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":false,"bcwiEnabled":false,"cuxdEnabled":true,"regaPoll":true,"regaInterval":"25","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048","queueTimeout":"5000","queuePause":"250","contextStore":""}]`

`

**Comment by hobbyquaker** [comment]
Betrifft das nur die Statusanzeige im Editor oder auch die Nachrichten selbst?

**Comment by Matten-Matten** [comment]
Auch die Nachrichten selbst

**Comment by hobbyquaker** [comment]
Konnte es "leider" nicht reproduzieren, aber ich hab ein Verdacht... Teste mal bitte ob das Problem mit 2.1.4 aus der Welt ist.

**Comment by stenki-eu** [comment]
Habe das gleiche Problem seit der Version 2.1.3. Mit einem manuell ausgelösten Ereigniss (inject) läßt sich aber das Phänomen nicht reproduzieren.

![2019-05-19 07_26_41](https://user-images.githubusercontent.com/39874856/57978158-8f5b5d00-7a07-11e9-8df6-fb498c95af4b.png)

![2019-05-19 07_31_16](https://user-images.githubusercontent.com/39874856/57978185-2de7be00-7a08-11e9-8ad3-e89df6d9053b.png)

Zur Kontrolle habe ich Home Assistant Baustein hinzugefügt, der exakt das gleiche Device aufruft.

Sobald vor get value ein anderer "bekannter" Knoten auftaucht wird der payload übernommen (nicht nur Anzeige). Im letzten Bild wurde presence detected von Home Assistant Note ausgelöst und schon hat wieder alles funktioniert.
![2019-05-19 07_41_56](https://user-images.githubusercontent.com/39874856/57978259-d6e2e880-7a09-11e9-8561-7b4907d8bf5a.png)

**Comment by hobbyquaker** [comment]
Ah Danke, das hat geholfen. Das Problem ist wohl dieser Change: https://github.com/rdmtc/node-red-contrib-ccu/commit/3eb37af0f140e7967b087b69fbb499db1700677f
Da werden iface/channel/datapoint überschrieben falls sie in der message vorhanden sind. Muss ich anders lösen, fix kommt asap.

**Comment by hobbyquaker** [comment]
@Matten-Matten @stenki-eu sollte mit 2.1.5 gefixt sein. Bitte gebt Bescheid ob es funktioniert.

**Comment by stenki-eu** [comment]
Mein kleines Beispiel von heute morgen funktioniert wieder wie erwartet 👍 
Für mehr Tests hat aber die Zeit nicht gereicht.

**Comment by Matten-Matten** [comment]
Ja funktioniert wieder! Vielen Dank!

Gruß
Matten Matten
