### ISSUE TITLE
Reconnect zu Schnittstellenprozessen funktioniert nicht

### ISSUE THREAD

**Issue by Markus-** [rdmtc/node-red-contrib-ccu#85]
Hallo zusammen,

ich habe gestern in meiner Testumgebung die Netzwerkverbindung meiner separaten Node Red Instanz getrennt und seit dem scheint der MQTT-Node auf "partly" connected zu sein.

Wenn ich die Flows neu starte und in meine Debug-Meldungen schaue sehe ich zwei Einträge die auffallen:
"de-init BidCos-RF http://10.30.0.13:2074 failed Error: connect ECONNREFUSED 10.20.0.2:2001"
"init BidCos-RF Error: connect ECONNREFUSED 10.20.0.2:2001"

Die 10.20.0.2 ist die CCU (Node Red hat 10.30.0.13) - Router & Firewall sollten soweit stimmen - normalerweise läuft es ja.

Jetzt hab ich per SSH auf die CCU geschaut und dort lauscht auch nichts auf 2001.

Ich bin mir ziemlich sicher, dass wenn ich die CCU2 neu starte alles wieder in Ordnung ist. Würde aber im Vorfeld gerne verstehen was hier passiert.

Kann ich das irgendwo nachvollziehbar in Logs / Messages sehen bzw. hat einer einen Tipp?

Danke und Gruß
Markus

**Comment by hobbyquaker** [comment]
Sieht so aus als ob der rfd auf Deiner CCU abgeschmiert ist. Dazu müsstest Du im CCU Syslog Meldungen finden.

**Comment by Markus-** [comment]
Ein Neustart des rfds ließ die CCU2 wieder auf dem Port lauschen. Der MQTT-Node hat leider scheinbar nicht versucht sich wieder zu verbinden - gibt es da eine Möglichkeit ohne Node-Red / die Flows zu "restarten"?

Gruß
Markus

**Comment by Markus-** [comment]
Gäb es hier die Möglichkeit einen Watchdog zu etablieren oder muss ich selbst was basteln?

**Comment by hobbyquaker** [comment]
der ccu-connection Node sollte spätestens nach PingInterval*2 die Verbindung automatisch wieder aufnehmen. Tut er das nicht wäre das ein Bug, dann bräucht ich mal ein Log auf Level Debug

**Comment by Markus-** [comment]
Welches Pinginterval meinst du?  RPC ping timeout (s) aus dem Konfigurationsknoten? Wenn ja habe ich das gerade mal auf 5s gestellt und manuell auf der CCU den rfd gestoppt (/etc/init.d/S61rfd stop). 

Ergebnis: 
ping timeout BidCos-RF 6
< BidCos-RF init Error: connect ECONNREFUSED 10.20.0.2:2001

Starte ich den rfd wieder erfolgt kein reconnect.

Welches Logfile meinst du?

Gruß
Markus

**Comment by hobbyquaker** [comment]
Habs eben mal selbst getestet, das ist ein Bug. Reconnect funktioniert nicht, ist bisher nur niemand aufgefallen. Wird asap gefixt.

**Comment by hobbyquaker** [comment]
@Markus- Ich hoffe das mit node-red-contrib-ccu 2.1.6 gefixt zu haben. Wenn Du nicht auf das nächste RedMatic Release warten willst kannst Du node-red-contrib-ccu auch vorab über den Node-RED Palette Manager updaten. Bitte gib Bescheid ob es funktioniert wie erwartet.

**Comment by Markus-** [comment]
Hab es eben mal getestet. Funktioniert einwandfrei. Mit dem hs485d ebenfalls.

Gruß
Markus
