### ISSUE TITLE
Mehrere Verbindungen: CCU2 -> Mehrere Node-Red-Instanzen

### ISSUE THREAD

**Issue by Markus-** [rdmtc/node-red-contrib-ccu#88]
Hallo,

kann ich zuverlässig mehreren NodeRed-Instanzen parallel auf die CCU2 zugreifen lassen inkl. Rückkanal?

Ich habe aktuell eine Instanz dauerhaft laufen und nutze diese als MQTT-Umsetzer.
Nun möchte ich eine zweite Instanz mit der CCU2 verbinden (andere "LISTEN-Address / anderer Port).

Funktioniert? Wenn ja wie läuft das technisch.

CCU2 meldet dann alle Aktionen an beide "angemeldeten" Endpunkte?
Gibt es eine Grenze an parallelen Clients für die API inkl. "Rückkanal"?

Danke und Gruß
Markus

**Comment by hobbyquaker** [comment]
Sollte funktionieren, ein Limit ist mir nicht bekannt. Die Schnittstellenprozesse unterscheiden die verschiedenen Subscriber anhand der Init URL (rfd,hs485d) oder Anhand des Init Identifiers (hmipserver). Beides ist unterschiedlich insofern Listen-Address und/oder Port sich unterscheiden.

**Comment by Markus-** [comment]
Ich werde es einfach mal Testen. 

Hoffe, dass es zuverlässig klappt - also beide Instanzen zeitgleich über die API informiert werden wenn bspw. ein Schalter gedrückt wird.
