### ISSUE TITLE
Fehler in der node-red-contrib-ccu, node signal

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/node-red-contrib-ccu#90]
Hallo Hobbyquaker,

folgender Fehler (vielleicht Bedienfehler) ist mir bei der Ansteuerung eines HM-OU-CFM-TW aufgefallen.

Wenn man auf Volumen auf "msg.payload" stellt geht es bei einem HMIP-MP3p aber nicht bei einem HM-OU-CFM-TW. Ich habe hierfür unten gezeigten "flow" verwendet. Beim HM-OU-CFM-TW habe ich auch festgestellt das hin und wieder sich der "msg.payload" verstellt (ohne mein Zutun). 

Gruß Thomas

![grafik](https://user-images.githubusercontent.com/44590735/61247382-3f6fec80-a751-11e9-8e9a-e728345ea6b6.png)

![grafik](https://user-images.githubusercontent.com/44590735/61247537-94abfe00-a751-11e9-906b-b5bd68fd84e4.png)

**Comment by ThomasLoeffel** [comment]
Hallo hobbyquaker,

sorry das ich ein Duplikat angelegt habe. Es war nur verschwunden und ich dachte ich hätte einen Fehler gemacht.

Gruß Thomas

**Comment by hobbyquaker** [comment]
@ThomasLoeffel 
> Wenn man auf Volumen auf "msg.payload" stellt geht es bei einem HMIP-MP3p aber nicht bei einem HM-OU-CFM-TW.

D.h. die Payloads die Du dann schickst werden einfach ignoriert und die Lautstärke wird nicht verändert?

 > Beim HM-OU-CFM-TW habe ich auch festgestellt das hin und wieder sich der "msg.payload" verstellt (ohne mein Zutun).
D.h die Konfiguration des Signal Nodes hat sich Anlasslos geändert und statt `msg.payload` war dann was konfiguriert?

Kannst Du mal ein JSON Export des Flows pasten bitte?

**Comment by hobbyquaker** [comment]
Ah, hab die Ursache gefunden, fix kommt.

**Comment by hobbyquaker** [comment]
sollte in 3.0.0-beta.4 behoben sein, bitte gib Bescheid ob es funktioniert.

**Comment by ThomasLoeffel** [comment]
Hallo Hobbyquaker,

ich warte seit Tagen das ich das "Update" angezeigt bekomme. Mache ich was falsch?
Lieben Gruß Thomas

PS. Meine derzeitige Version ist 3.0.0 beta.2

**Comment by hobbyquaker** [comment]
Hmm, die 3.0.0-beta.4 ist im Node-RED Katalog erfasst, die "sollte" Dir "eigentlich" angeboten werden. Versuch mal noch mal Node-RED Neustart und Browser-Cache leeren und schau ob es dann geht.

**Comment by ThomasLoeffel** [comment]
Hallo Hobbyquaker,

ich habe es mit zwei verschiedenen Browsern probiert und natürlich den Chache gelöscht. Leider kein Erfolg. Beta 5 wird nicht angeboten. Hast Du noch einen Tip?

Gruß Thomas

**Comment by ThomasLoeffel** [comment]
Habe es auch auf meinem Backupsystem probiert. Findet Beta 5 auch nicht.
Gruß Thomas

**Comment by Sineos** [comment]
Seltsam. Mir wird Beta 5 angezeigt.
Alternativ manuell installieren: https://github.com/rdmtc/RedMatic/wiki/Node-Installation#installation-via-npm-auf-der-kommandozeile

Der letzte Befehl sollte so aussehen:
`npm install --save --no-package-lock --global-style --save-prefix="~" --production https://github.com/rdmtc/node-red-contrib-ccu/archive/v3.0.0-beta.5.tar.gz`

**Comment by ThomasLoeffel** [comment]
Hallo Sineos,

ich habe es auch unter Iobroker probiert. Ging auch nicht. Mit Deinem Weg hat es geklappt.
So nun teste ich den Punkt.

Lieben Gruß Thomas

**Comment by ThomasLoeffel** [comment]
Hallo Zusammen,

ich kann bestätigen das mit Beta 5 dieser Punkt behoben ist und die Lautstärke mit msg.payload übertragen werden kann.

Gruß Thomas
