### ISSUE TITLE
Input beim "get value"-Node verarbeiten

### ISSUE THREAD

**Issue by FordAndii** [rdmtc/node-red-contrib-ccu#91]
Hallo, es würde mir sehr helfen, wenn der "get value"-Node den Input der eingehenden Message genau so verarbeiten könnte wie der "value"-Node. Das scheint bisher nicht so zu sein und in der Dokumentation habe ich diesbezüglich nichts gefunden.

Konkret wäre es schön, wenn ich per msg.interface, msg.channel, msg.datapoint oder msg.topic die Feldwerte des "get value"-Nodes setzen könnte.

Beste Grüße und danke für die tolle Arbeit!

**Comment by hobbyquaker** [comment]
Das sollte bereits funktionieren, ist nur nicht dokumentiert. Du kannst die properties `iface`, `channel`, `datapoint` und `sysvar` über eingehende Messages setzen - dafür müssen allerdings die entsprechenden Konfigoptionen leer belassen werden.

**Comment by FordAndii** [comment]
Hmm, ich bekomme es leider nicht hin. Ich möchte das LEVEL von Kanal 4 eines HmIP-BROLL auslesen.

Ich setze mittels eines function-Nodes die Werte msg.channel (exakt wie bei einem value-Node, bei dem es wie oben beschrieben funktioniert) und msg.datapoint auf "LEVEL". Im getValue-Node lasse ich die beiden Felder "Channel" und "Datapoint" leer und setze "Interface" auf "HmIP-RF".

Der Debug-Node sagt: "TypeError: Cannot read property 'value' of undefined"

**Comment by hobbyquaker** [comment]
dann gibts da noch ein Bug, ich schau asap danach

**Comment by hobbyquaker** [comment]
@FordAndii kannst Du mir mal ein Screenshot der Konfiguration des get value Nodes zeigen?

**Comment by hobbyquaker** [comment]
Hab zwei Änderungen vorgenommen die nun in v3.0.0-beta.5 stecken:
* Beim Kanal wird nun (ebenso wie in allen anderen Nodes) nach dem Leerzeichen abgeschnitten. Falls Du in Deiner Nachricht nicht nur den Kanal sondern auch einen durch Leerzeichen abgetrennten Bezeichner im `channel` Attribut hattest ist das jetzt kein Problem mehr
* Wird der Kanal bzw. die Systemvariable nicht gefunden wird nun eine Aussagekräftige Fehlermeldung zurückgegeben.

**Comment by FordAndii** [comment]
Danke, es lag tatsächlich an dem Leerzeichen im channel-Attribut. Mit der neuen Version funktioniert es!
