### ISSUE TITLE
Nach Neustart der CCU wird das RPC-Event nicht ausgeführt

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/node-red-contrib-ccu#93]
Hallo Hobbyquaker,

ggf. schreibe eine bekannte Sache auf. Ich habe extra geschaut, aber nichts gefunden.

Problem:
Ich lasse über ein RPC Event "globale Variablen" setzen. Nach einem CCU Neustart macht das RPC Event dieses aber nicht. In der CCU stehen in der WEBUI die richtigen Werte (z.B. HMIP-SWDO Fenstersensor), in den Variablen aber nicht. Nach einem Neustart der Redmatic (über den Button) funktioniert es wieder.

Was mache ich falsch?

Gruß Thomas

**Comment by ThomasLoeffel** [comment]
![grafik](https://user-images.githubusercontent.com/44590735/63222498-22dc2f80-c1a9-11e9-822d-bd4554a68fa5.png)

**Comment by ThomasLoeffel** [comment]
![grafik](https://user-images.githubusercontent.com/44590735/63222505-3be4e080-c1a9-11e9-8abd-60ca1c645d12.png)

**Comment by hobbyquaker** [comment]
Duplicate https://github.com/rdmtc/RedMatic/issues/233

**Comment by hobbyquaker** [comment]
Kann den Bug bestätigen, ist auf der Todo.

**Comment by hobbyquaker** [comment]
@ThomasLoeffel Hab eben versucht das zu reproduzieren, ohne "Erfolg", bei mir funktioniert das auch nach einem CCU Neustart, sobald Node-RED den Flow gestartet hab kommt die Nachricht raus.

Folgenden Testflow hab ich verwendet:
```
[{"id":"f744ff7a.374e1","type":"debug","z":"78e2b76c.10f7f8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":490,"y":260,"wires":[]},{"id":"8fa85103.aa4d9","type":"file","z":"78e2b76c.10f7f8","name":"","filename":"/usr/local/addons/redmatic/var/testlog.log","appendNewline":true,"createDir":false,"overwriteFile":"false","encoding":"none","x":580,"y":320,"wires":[[]]},{"id":"f9394b1f.5ae8f8","type":"function","z":"78e2b76c.10f7f8","name":"","func":"msg.payload = (new Date()) + ' ' + JSON.stringify(msg);\nreturn msg;","outputs":1,"noerr":0,"x":290,"y":320,"wires":[["8fa85103.aa4d9","f744ff7a.374e1"]]},{"id":"397230f6.522fc","type":"inject","z":"78e2b76c.10f7f8","name":"","topic":"Flow Start!","payload":"","payloadType":"str","repeat":"","crontab":"","once":true,"onceDelay":0.1,"x":210,"y":400,"wires":[["f9394b1f.5ae8f8"]]},{"id":"aaf0db85.26e388","type":"ccu-value","z":"78e2b76c.10f7f8","name":"","iface":"BidCos-RF","channel":"KEQ0165114:1 HM-Sec-SC KEQ0165114:1","datapoint":"STATE","mode":"","start":true,"change":false,"cache":true,"queue":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":190,"y":240,"wires":[["f9394b1f.5ae8f8"]]},{"id":"38263145.35ea0e","type":"ccu-connection","z":"","name":"localhost","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":false,"cuxdEnabled":false,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048"}]
```
![image](https://user-images.githubusercontent.com/2503307/63639327-19affe80-c692-11e9-82a7-ba527d44e405.png)
![image](https://user-images.githubusercontent.com/2503307/63639330-216fa300-c692-11e9-8708-ab4b8083d4a5.png)

Kannst Du mal bitte probieren mit diesem Testflow das zu reproduzieren und mir dann das RedMatic Log auf Debug Level sowie diese testlog Datei zukommen lassen?

**Comment by ThomasLoeffel** [comment]
Hallo Hobbyquaker,

so habe nun ein bisschen Zeit und versuche mit Deinem Flow zu testen. Danke Dir!!

Gruß Thomas
