### ISSUE TITLE
Can I use your RedMatic HomeKit add on with this Node Red node for debmatic CCU?

### ISSUE THREAD

**Issue by markusmaker** [rdmtc/node-red-contrib-ccu#94]
As I use debmatic for my CCU how can I use your HomeKit RedMatic add on ?

**Comment by hobbyquaker** [comment]
yes, but it will not show up in the Node-RED palette manager. You will have to install it manually with npm.

**Comment by markusmaker** [comment]
Thanks.
For others: 
npm i redmatic-homekit
