### ISSUE TITLE
timezone for previousValue incorrect

### ISSUE THREAD

**Issue by aunovis-kretschmer** [rdmtc/node-red-contrib-ccu#95]
Hey all, 
thanks for the project!
It seems, the tsPrevious value has the wrong timezone set. :(

Both timestamps should be 15:xx. 

![Unbenannt](https://user-images.githubusercontent.com/50730307/63945814-5013c200-ca74-11e9-8fb5-62e2c9437ca3.PNG)

it seems, that this is not always happening.

**Comment by hobbyquaker** [comment]
@aunovis-kretschmer did this occur on a datapoint (_value_, _get value_ or _rpc event_ node) or on a ccu variable (_sysvar_ node)?
