### ISSUE TITLE
Connection with Authentication enabled

### ISSUE THREAD

**Issue by ed-holland** [rdmtc/node-red-contrib-ccu#97]
I'm running Node-Red seperately from my RaspberryMatic in docker.
Currently, Node-Red is the only connection that requires the disabling of the authentication.

All other connections to RaspberryMatice are with User/Pwd

Can the connection be extended similarly to how it is done for MQTT?

**Comment by hobbyquaker** [comment]
Can be done, sure. But hasn't high priority for me atm because for RedMatic users (which is the primary audience of node-red-contrib-ccu)  this is not an issue (there it also works with auth enabled due to local connect). Will implement this in future, but can't promise when.

**Comment by soosp** [comment]
+1 We use our RaspberryMatic in and relativly unsafe environment, so authenticated and SSL/TLS secured connections are mandatory.

**Comment by Mingendahl** [comment]
+1 for me, too!

**Comment by hobbyquaker** [comment]
Thanks @Konrni - TLS and Auth is supported starting with v3.4.0
