### ISSUE TITLE
Problem mit RPC-Node seit dem neuesten Update 3.47.15.20190831

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/node-red-contrib-ccu#98]
Hallo Hobbyquaker,

bei mir passieren komische Sachen.....
1) Die Node "get-value" findet die Variable DutyCycle nicht mehr. Erst wenn ich den Asus Tinker neu boote geht dieses wieder.
![grafik](https://user-images.githubusercontent.com/44590735/64562103-7e36b300-d34c-11e9-9690-13f4a739e162.png)
2) Ich spiele gerade mit der Heizungssteuerung herum. Ggf sind dann auch erst die Probleme aufgetreten..... weiss ich nicht mehr genau.
![grafik](https://user-images.githubusercontent.com/44590735/64562381-2a789980-d34d-11e9-951a-be1ad5f01d84.png)

Wenn ich nun versuche die Node "set-value" zu nutzen passiert folgendes. Ich gebe alles ein, kann dieses auch auswählen, aber es speichert nicht. Also nach fertig: alles leer!
![grafik](https://user-images.githubusercontent.com/44590735/64562297-fb622800-d34c-11e9-970b-14fd35270c51.png)

Nach "Fertig" klicken.....
![grafik](https://user-images.githubusercontent.com/44590735/64562556-8fcc8a80-d34d-11e9-8594-841981f1a0ea.png)

Ich bin ein bissschen frustriert. Mache ich was falsch? Oder stimmt da was nicht?
Gruß Thomas

**Comment by ThomasLoeffel** [comment]
Zu Punkt 1: Wenn der Eingang aktualisiert wird, scheint der Fehler zu verschwinden.
Zu Punkt 2: Besteht trotz Reboot, Neustart usw. immer noch. Spiele auf meinem Backupsystem gerade die Version: 3_47_10_20190713 auf und schaue was da passiert...... So selbe Folge. Node-RPC zeigt das Verhalten, das keine Auswahl erhalten bleibt, nachdem man "Fertig" geklickt hat. Mir ist in diesem Zusammenhang noch aufgefallen, dass man eine gemachte Auswahl nicht mehr löschen kann (sie wird zwar nicht abgespeichert, aber nach Auswahl keine Änderung mehr möglich).

Gruß Thomas

PS. Version CCU, 3.0.0-beta.5

**Comment by ThomasLoeffel** [comment]
Ergänzung:
Auch auf IOBROKER mit der Version 3.0.-beta.5 habe ich Probleme mit dem RPC.

**Comment by ThomasLoeffel** [comment]
Hallo Hobbyquaker,
durch die Hilfe von meinem Bruder (dort ist die Version 2.1.6 installiert (dort klappt es)) kam ich auf die Idee einmal zu downgraden bis es geht.

3.0.0 beta5 -> nein
3.0.0 beta4 -> nein
3.0.0 beta3 -> ja Fehler scheint nicht mehr da zu sein
............

Mit der Version 3.0.0 beta3 gingen auch wieder die Filter und er zeigte die richtige Auswahl an. Ich gehe nach einem Backup mal auf meinem Hauptsystem auf 3.0.0 beta3 runter und schaue ob die RPC Fehler nun auch verschwunden sind.

Gruß Thomas

![grafik](https://user-images.githubusercontent.com/44590735/64921999-d09f2600-d7c9-11e9-8d3c-9178576e0328.png)

**Comment by ThomasLoeffel** [comment]
Hallo lieber Hobbyquaker,

brauchst Du noch etwas oder ist der Fall aus Deiner Sicht klar?
Gruß Thomas

**Comment by hobbyquaker** [comment]
Muss noch um Geduld bitten, Ich versuch mich baldmöglichst drum zu kümmern.

**Comment by ThomasLoeffel** [comment]
Hallo Hobbyquaker,

wollte "natürlich" keinen Druck machen. Wir war es nur wichtig ob ich Dir mit irgend etwas noch helfen kann. Danke für Deine super Arbeit!

Gruß Thomas

**Comment by hobbyquaker** [comment]
> die Node "get-value" findet die Variable DutyCycle nicht mehr

Ich vermute Du triggerst den Node an bevor die Verbindung zur Rega steht. Ist das ein Inject-Node der direkt nach dem Deploy den Flow triggert? Falls ja bau da mal eine Verzögerung ein.

> Wenn ich nun versuche die Node "set-value" zu nutzen passiert folgendes. Ich gebe alles ein, kann dieses auch auswählen, aber es speichert nicht. Also nach fertig: alles leer!

Die 3.0.0-beta Versionen wurden an Node-RED 1.0 angepasst und sind nicht mehr voll kompatibel mit Node-RED 0.20. Leider vergessen das ins Readme zu schreiben.

**Comment by ThomasLoeffel** [comment]
Ah verstehe jetzt. Samstag kommt dann ja die 1.0 habe ich gelesen. Gibt es denn noch eine neue 3.0.0, oder kann ich diese dann einfach wieder installieren?

Gruß Thomas

**Comment by hobbyquaker** [comment]
@ThomasLoeffel Du kannst auch jetzt schon auf die 5.0.0-beta.9 updaten. Mir sind bisher keine Bugs begegnet, falls ich bis Samstag keine find werde ich die quasi unverändert als finale 5.0.0 veröffentlichen.

**Comment by ThomasLoeffel** [comment]
@Hobbyquaker,
danke habe es auf dem Testsystem mal installiert. Auf die schnelle ist mir nur aufgefallen das "Implementieren" nun wieder "Deploy" heisst.

Super Arbeit, ich teste weiter.
Gruß Thomas

**Comment by hobbyquaker** [comment]
@ThomasLoeffel passt nun alles? Können wir hier schließen?

**Comment by ThomasLoeffel** [comment]
Hallo Hobbyquaker,

scheint alles ok zu sein. Danke Dir :-)

Gruß Thomas
