### ISSUE TITLE
Unable to remove CCU connection

### ISSUE THREAD

**Issue by sander76** [rdmtc/node-red-contrib-ccu#99]
When deleting all CCU nodes, node-red still tries to connect to the server in the background.
This should not happen.

**Comment by hobbyquaker** [comment]
Did you delete the "ccu connection" node also (this is a config node)? (see https://github.com/rdmtc/RedMatic/wiki/CCU-Nodes#ccu-connection-node on how to get into it's configuration dialog)

**Comment by sander76** [comment]
@hobbyquaker Ah! I missed that. Thanks for this great plugin!
